# Generated by Django 2.1 on 2019-10-26 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=80)),
                ('shares', models.IntegerField(default=0)),
                ('buy_price', models.FloatField(default=0.0)),
                ('date_lastupdated', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('date_lastupdated', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users'),
        ),
    ]
