# Generated by Django 2.1 on 2019-11-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191110_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
