# Generated by Django 2.1 on 2019-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpicker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('ticker_symbol', models.CharField(max_length=4)),
                ('timestamp', models.CharField(max_length=30)),
                ('open', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('volume', models.IntegerField(default=0)),
                ('date_lastupdated', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Adobe_Inc',
        ),
    ]
