# Generated by Django 2.1 on 2019-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpicker', '0002_auto_20191026_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
