# Generated by Django 2.1 on 2019-11-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpicker', '0003_auto_20191109_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_data',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
