# Generated by Django 2.1 on 2019-11-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpicker', '0004_stock_data_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('shares', models.IntegerField(default=0)),
                ('ticker_symbol', models.CharField(max_length=4)),
                ('purchase_timestamp', models.DateField(max_length=30)),
                ('purchase_price', models.FloatField(default=0.0)),
                ('date_lastupdated', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='stock_data',
            old_name='open',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='stock_data',
            name='shares',
        ),
    ]
