# Generated by Django 2.2.5 on 2019-12-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpicker', '0007_account_predictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_prediction_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('close', models.FloatField(default=0.0)),
                ('predicted', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='predictions',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
    ]
