# Generated by Django 2.2.5 on 2019-12-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpicker', '0009_auto_20191201_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='companylist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
