# Generated by Django 2.2.5 on 2019-12-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpicker', '0010_companylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictions',
            name='high',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='low',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='open',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='volume',
        ),
        migrations.AddField(
            model_name='predictions',
            name='prediction',
            field=models.FloatField(default=0.0),
        ),
    ]
